sequenceDiagram
		autonumber
		participant Dev as Developer
		participant Repo as Git Repo
		participant Pipeline as Azure Pipeline
		participant Backend as Backend Job
		participant Frontend as Frontend Job
		participant Artifacts as Artifacts Job