mindmap
  root((AppComponent))
    Components
      Banner(BannerComponent)
      Sidebar(SidebarComponent)
      Weather(WeatherComponent)
      Grid[backend-weather.grid.ts]
    Service
      WeatherSvc(WeatherService)
    Interfaces
      HelloResponse(HelloResponse.interface.ts)
      WeatherTypes(weather.interfaces.ts)
    Config
      RootAppConfig(app.config.ts)
      ConfigFolderAppConfig(config/app.config.ts)
    Shared
      Icons(svg-icons.ts)
